# Jekyll Resume Theme
url: "http://pa1pal.github.io"
# Site settings
title: Pawan Pal
email: pawanpal004@gmail.com
description: Hi I'm Pawan Pal.
baseurl: ""
url: "http://pa1pal.github.io"
name: Pawan Pal
job: Android Developer
location: New Delhi, India
languages: HTML, CSS and Javascript
twitter_username: pa1pal
github_username:  pa1pal
codepen_username:  pa1pal
email_address: pawanpal004@email.com
copyright: ©Pawan Pal Powered by Jekyll and hosted on Github Pages

# Build settings
markdown: kramdown
